### ISSUE TITLE
OffScreenGlThread

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/Stream-USB-test#12]
I am trying to update USBBase.java to latest com.serenegiant.usb.UVCCamera 

This library has latest UVCCamera

implementation 'com.herohan:UVCAndroid:1.0.7'

Now I am facing problem with the OffScreenGlThread, like to know how to implement the OffScreenGlThread or alternate for that class

    public USBBase(Context context) {
        this.context = context;
        glInterface = new OffScreenGlThread(context);
        //glInterface.init();
       // cameraManager = new Camera1ApiManager(glInterface.getSurfaceTexture(), context);
        init();
      }

**Comment by pedroSG94** [comment]
Hello,

Currently, use StreamBase and create your own VideoSource for usb camera is recommended instead of use that class. You have a branch with an implementation for it:
https://github.com/pedroSG94/RootEncoder/tree/feature/extra-video-source/app/src/main/java/com/pedro/streamer/rotation

Use that branch to test it. You can change the video source using the menu in rotate example.

**Comment by pedroSG94** [comment]
I did a new branch updated to the library suggested because that library support android 14. This is the branch:
https://github.com/pedroSG94/RootEncoder/tree/feature/usb-camera

Install app example in that branch and use rotation example. In the menu you can change to camera UVC on fly.

Closing this issue as solved. Please avoid use this project because it is unmaintained.
